// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlakDukkani.Siniflar;

#nullable disable

namespace PlakDukkani.Migrations
{
    [DbContext(typeof(PlakDukkaniDbContext))]
    [Migration("20230109145552_ilk")]
    partial class ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlakDukkani.Siniflar.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AlbumAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IndirimOrani")
                        .HasColumnType("int");

                    b.Property<string>("SanatciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SatisDurum")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Albumler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumAd = "Bir Başka Sevgiliyi Sevemem Sevemem",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3896),
                            Fiyat = 250m,
                            IndirimOrani = 20,
                            SanatciAdi = "Erol Büyükburç",
                            SatisDurum = true
                        },
                        new
                        {
                            Id = 2,
                            AlbumAd = "Mavi",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3910),
                            Fiyat = 230m,
                            IndirimOrani = 0,
                            SanatciAdi = "Emel Sayın",
                            SatisDurum = false
                        },
                        new
                        {
                            Id = 3,
                            AlbumAd = "Yazık Oldu Yarınlara",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3912),
                            Fiyat = 200m,
                            IndirimOrani = 10,
                            SanatciAdi = "İlhan İrem",
                            SatisDurum = false
                        },
                        new
                        {
                            Id = 4,
                            AlbumAd = "O Ağacın Altı",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3913),
                            Fiyat = 280m,
                            IndirimOrani = 0,
                            SanatciAdi = "Zeki Müren",
                            SatisDurum = true
                        },
                        new
                        {
                            Id = 5,
                            AlbumAd = "Nedir Benim Günahım",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3914),
                            Fiyat = 210m,
                            IndirimOrani = 25,
                            SanatciAdi = "Gönül Akkor",
                            SatisDurum = true
                        },
                        new
                        {
                            Id = 6,
                            AlbumAd = "Aşk Başlarken",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3915),
                            Fiyat = 300m,
                            IndirimOrani = 25,
                            SanatciAdi = "Erol Evgin",
                            SatisDurum = false
                        },
                        new
                        {
                            Id = 7,
                            AlbumAd = "Söz Verirsin Severek",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3916),
                            Fiyat = 300m,
                            IndirimOrani = 0,
                            SanatciAdi = "Zeki Müren",
                            SatisDurum = false
                        },
                        new
                        {
                            Id = 8,
                            AlbumAd = "Gönül Dağı",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3917),
                            Fiyat = 250m,
                            IndirimOrani = 0,
                            SanatciAdi = "Neşet Ertaş",
                            SatisDurum = true
                        },
                        new
                        {
                            Id = 9,
                            AlbumAd = "Frank Sinatra",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3919),
                            Fiyat = 250m,
                            IndirimOrani = 10,
                            SanatciAdi = "Frank Sinatra",
                            SatisDurum = false
                        },
                        new
                        {
                            Id = 10,
                            AlbumAd = "Hoş Gör Sen",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3920),
                            Fiyat = 320m,
                            IndirimOrani = 25,
                            SanatciAdi = "Ajda Pekkan",
                            SatisDurum = true
                        },
                        new
                        {
                            Id = 11,
                            AlbumAd = "Merhaba Gençler",
                            CikisTarihi = new DateTime(2023, 1, 9, 17, 55, 52, 146, DateTimeKind.Local).AddTicks(3921),
                            Fiyat = 210m,
                            IndirimOrani = 10,
                            SanatciAdi = "Cem Karaca",
                            SatisDurum = false
                        });
                });

            modelBuilder.Entity("PlakDukkani.Siniflar.Yonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Yoneticiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KullaniciAdi = "admin1",
                            Sifre = "!:ASdfg1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
